### introduction to Pytorch

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import numpy as np
import torch

## Tensorの基本的な扱い方

In [ ]:
# CPU上にtensorを作成
t = torch.tensor([[1, 2], [3, 4.]])

In [3]:
# GPU上に作成もできる
t = torch.tensor([[1, 2], [3, 4.]], device='cuda:0')

In [4]:
# dtypeの指定も可能
t = torch.tensor([[1, 2], [3, 4.]], dtype=torch.float64)

In [6]:
# 1次元tensorの生成
t = torch.arange(0, 10)
t

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
# 100行10列tensorの作成
t = torch.zeros(100, 10).to("cuda:0")
t[:5]

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], device='cuda:0')

In [10]:
t.size()

torch.Size([100, 10])

In [14]:
# numpy配列への変換
t = torch.tensor([[1, 2], [3, 4.]])

print(type(t.numpy()))
t.numpy()

<class 'numpy.ndarray'>


array([[1., 2.],
       [3., 4.]], dtype=float32)

In [19]:
# cudaにいるtensorは一度cpuにコピーしてから渡す
torch.tensor([[1, 2], [3, 4.]], device='cuda:0')
t.to('cpu').numpy().astype('int32')

array([[1, 2],
       [3, 4]], dtype=int32)

In [20]:
t = torch.tensor([[1, 2, 3], [4, 5, 6.]])

#(0, 2)成分の抽出
t[0, 2]

tensor(3.)

In [22]:
# 全行の1列目まで
t[:, :2]

tensor([[1., 2.],
        [4., 5.]])

In [27]:
# 全行の1, 3列目を抽出する
t[:, [0, 2]]

tensor([[1., 3.],
        [4., 6.]])

In [29]:
# マスク配列を用いて条件抽出
t[t > 2]

tensor([3., 4., 5., 6.])

In [31]:
# 特定の成分に値を代入する
t[0, 1] = 100
t

tensor([[  1., 100.,   3.],
        [  4.,   5.,   6.]])

In [32]:
# 2列目に値を代入
t[:, 1] = 200
t

tensor([[  1., 200.,   3.],
        [  4., 200.,   6.]])

In [34]:
# マスクした条件に値を代入
t[t > 10] = 20
t

tensor([[ 1., 20.,  3.],
        [ 4., 20.,  6.]])

### 配列に施せる関数

In [35]:
v = torch.tensor([1, 2, 3.])
w = torch.tensor([0, 10, 20.])
m = torch.tensor([[0, 1, 2], [100, 200, 300.]])

In [38]:
# torchに大体の計算メソッドは実装されている
X = torch.randn(100, 10)

y = X * 2 + torch.abs(X)
X.mean()

tensor(-0.0176)

### 配列演算

In [39]:
x1 = torch.tensor([[1, 2], [3, 4.]])
x2 = torch.tensor([[10, 20, 30], [40, 50, 60.]])

# 4行1列
x1.view(4, 1)

tensor([[1.],
        [2.],
        [3.],
        [4.]])

In [40]:
#-1は残りの次元全てを表す. 
x1.view(1, -1)

tensor([[1., 2., 3., 4.]])

In [41]:
# 配列の転置
x2.t()

tensor([[10., 40.],
        [20., 50.],
        [30., 60.]])

In [45]:
# 列方向の追加
torch.cat([x1, x2], dim=1)

tensor([[ 1.,  2., 10., 20., 30.],
        [ 3.,  4., 40., 50., 60.]])

In [58]:
# 行方向の追加
torch.cat([x1, x2[:, :2]], dim=0)

tensor([[ 1.,  2.],
        [ 3.,  4.],
        [10., 20.],
        [40., 50.]])

In [59]:
# 別の次元の方向に追加
torch.stack([x1, x2[:, :2]])

tensor([[[ 1.,  2.],
         [ 3.,  4.]],

        [[10., 20.],
         [40., 50.]]])

### 行列演算

In [60]:
m = torch.randn(100, 10)
v = torch.randn(10)

In [62]:
# inner product
torch.dot(v, v)

tensor(12.8022)

In [64]:
torch.mv(m, v)

tensor([-8.8615,  4.1298,  4.5642,  3.6427, -8.3503, -4.3672,  1.5585, -3.0483,
         0.7228, -3.3096,  3.9345, -1.2935,  2.9730,  1.1271, -0.3214, -3.6827,
         5.2242,  2.7277, -3.4079, -7.7144, -2.0086, -5.7283,  5.0044, -5.1620,
        -5.1984,  2.7811, -1.6827,  3.9080,  2.6474, -2.2223, -2.3598, -1.4582,
        -0.5618, -1.6250, -1.2867,  2.0605,  3.2261, -1.1061, -4.2572,  6.0964,
        -1.1011, -0.9918,  3.3736, -3.4188, -3.5303, -3.7913, -6.0009,  1.0736,
         0.9499, -1.4902, -4.1055, -0.1191, -1.2654,  2.5569, -2.7650,  1.8820,
         2.3176,  9.5766, -0.1046,  0.7907, -0.5312, -0.1427, -5.5296, -3.5344,
        -3.1309,  2.4038, -1.9640,  3.0653,  0.8319, -1.7990,  4.1624, -0.1764,
         3.3693, -2.6315,  5.5209, -1.3534, -4.9427, -6.1125,  1.1144, -2.1538,
        -3.2395,  0.5547, -2.7404,  4.4746,  4.3559,  1.5947, -2.5850, -0.6809,
        -5.0432,  2.3292,  1.1448, -1.9228,  4.2001,  0.4616,  1.7807, -4.4102,
        -0.3913, -3.5719, -2.4670, -0.21

In [65]:
torch.mm(m.t(), m)

tensor([[106.2941, -23.0111,  -7.6969,  -3.7417,  -7.4390,  22.7478,  -9.4914,
         -14.5469,   6.3616,   0.6749],
        [-23.0111,  91.2658,   2.0541,   3.8072,   6.6799,   3.6642,   1.6067,
          -3.5301,   3.5759,   0.5518],
        [ -7.6969,   2.0541,  94.1391,  -5.4542,  -1.2200,   6.8423,  -2.4177,
          15.3306,   6.6767,  -4.8784],
        [ -3.7417,   3.8072,  -5.4542,  81.2652,  -2.4326,  -6.2608,   6.1808,
          -4.2001,  -2.2607,   4.7597],
        [ -7.4390,   6.6799,  -1.2200,  -2.4326, 100.5765,   5.6041,  -8.7475,
         -10.4686, -15.3753,   4.3326],
        [ 22.7478,   3.6642,   6.8423,  -6.2608,   5.6041,  97.2567,  -5.4126,
           3.9500,   2.0603,   3.3870],
        [ -9.4914,   1.6067,  -2.4177,   6.1808,  -8.7475,  -5.4126, 116.9593,
          10.5793,   6.7770, -14.6941],
        [-14.5469,  -3.5301,  15.3306,  -4.2001, -10.4686,   3.9500,  10.5793,
         109.2883,   9.2543,   1.6052],
        [  6.3616,   3.5759,   6.6767,  -2.2607,

In [71]:
# 特異値分解
u, s, v = torch.svd(m)
print(u.size())
print(s.size())
print(v.size())

torch.Size([100, 10])
torch.Size([10])
torch.Size([10, 10])


In [74]:
symm = torch.mm(m.t(), m)
# 固有値分解
torch.eig(symm)

tensor([[106.2941, -23.0111,  -7.6969,  -3.7417,  -7.4390,  22.7478,  -9.4914,
         -14.5469,   6.3616,   0.6749],
        [-23.0111,  91.2658,   2.0541,   3.8072,   6.6799,   3.6642,   1.6067,
          -3.5301,   3.5759,   0.5518],
        [ -7.6969,   2.0541,  94.1391,  -5.4542,  -1.2200,   6.8423,  -2.4177,
          15.3306,   6.6767,  -4.8784],
        [ -3.7417,   3.8072,  -5.4542,  81.2652,  -2.4326,  -6.2608,   6.1808,
          -4.2001,  -2.2607,   4.7597],
        [ -7.4390,   6.6799,  -1.2200,  -2.4326, 100.5765,   5.6041,  -8.7475,
         -10.4686, -15.3753,   4.3326],
        [ 22.7478,   3.6642,   6.8423,  -6.2608,   5.6041,  97.2567,  -5.4126,
           3.9500,   2.0603,   3.3870],
        [ -9.4914,   1.6067,  -2.4177,   6.1808,  -8.7475,  -5.4126, 116.9593,
          10.5793,   6.7770, -14.6941],
        [-14.5469,  -3.5301,  15.3306,  -4.2001, -10.4686,   3.9500,  10.5793,
         109.2883,   9.2543,   1.6052],
        [  6.3616,   3.5759,   6.6767,  -2.2607,

torch.return_types.eig(eigenvalues=tensor([[148.2764,   0.0000],
        [134.5190,   0.0000],
        [ 58.9755,   0.0000],
        [121.7397,   0.0000],
        [107.9814,   0.0000],
        [100.5869,   0.0000],
        [ 97.5308,   0.0000],
        [ 73.6492,   0.0000],
        [ 79.1343,   0.0000],
        [ 82.3697,   0.0000]]), eigenvectors=tensor([]))

### 自動微分

In [75]:
x = torch.randn(100, 3)
a = torch.tensor([1, 2, 3.], requires_grad=True)

y = torch.mv(x, a)
o = y.sum()

# 微分の実行
o.backward()

In [79]:
o != x.sum(0)

tensor([True, True, True])

In [77]:
x.grad is None

True